### ISSUE TITLE
Update About me

### ISSUE THREAD

**Issue by osteoarchaeo** [TheBiggerGuy/com.chelsislotten.www#14]
Should now read: "Chelsi Slotten recieved her PhD in anthropology from American University. She received her BA from Tulane University in New Orleans where she studied human osteology, forensics, and the classics. She then went on to complete her MSc in paleopathology at Durham University in England. Her research there focused on recognizing victims of domestic abuse in the archaeological record and identifying social, religious, political, and economic factors contributing to different prevalence rates between urban and rural populations. Her current research interests include how gender influences bioarchaeology, nutritional access, health frailty, and trauma during the Viking Era. Her dissertation analyzes how gender shaped individuals lived experiences during the Danish Viking Age. She also has a passion for understanding with how the public engages with the past particularly at museums. "

Also make it so the words don't hyphenate if they are too long for the line.

**Comment by TheBiggerGuy** [comment]
Fixed in #26
