### ISSUE TITLE
Links should open in a new page 

### ISSUE THREAD

**Issue by osteoarchaeo** [TheBiggerGuy/com.chelsislotten.www#49]
I think this is mostly for the publications and presentation page. Maybe also the Figma link in my portfolio

**Comment by osteoarchaeo** [comment]
Prioritize opening portfolio links in a new page. Figma link for the museum app, Adobe links for the enchanted and food waste portfolios.

**Comment by osteoarchaeo** [comment]
I am a genius and I fixed this in my local version!!!!!!!

**Comment by TheBiggerGuy** [comment]
fixed in https://github.com/TheBiggerGuy/com.chelsislotten.www/pull/63

**Comment by TheBiggerGuy** [comment]
@osteoarchaeo is this now fixed?

**Comment by osteoarchaeo** [comment]
Fixed!
