### ISSUE TITLE
Columns

### ISSUE THREAD

**Issue by osteoarchaeo** [TheBiggerGuy/com.chelsislotten.www#62]
Columns no longer seem to be working

**Comment by TheBiggerGuy** [comment]
The bug
![Screenshot from 2021-07-27 21-36-49](https://user-images.githubusercontent.com/152316/127223969-4ee787e5-3e75-4fa3-97b9-6deb136373c1.png)

**Comment by TheBiggerGuy** [comment]
fixed in https://github.com/TheBiggerGuy/com.chelsislotten.www/pull/64

**Comment by TheBiggerGuy** [comment]
![Screenshot from 2021-07-27 21-44-17](https://user-images.githubusercontent.com/152316/127224811-01d3245b-90ac-4eac-a085-d1f66c737fc7.png)

**Comment by TheBiggerGuy** [comment]
@osteoarchaeo can this be closed?

**Comment by osteoarchaeo** [comment]
You're amazing!!!
